channels:
  - defaults
dependencies:
  - pip>=20.3.3
  - python=3.9
  - pip:
      - requests
      - sphinx-book-theme>=0.1.3
      - jinja2>=2.11.3
      - sphinxcontrib-programoutput>=0.17
      - showyourwork
