channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.11
  - pyyaml
  - requests
  - sphinx-book-theme
  - jinja2
  - sphinx-design
  - sphinxcontrib-programoutput
  - towncrier
  - pip:
    - sphinx-changelog
