channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip=21.0.1
  - tectonic=0.8.0
  - mamba=0.17.0
  - snakemake-minimal=6.15.5
  - pip:
      - click==8.0.4
      - pyyaml==6.0
      - requests==2.25.1
      - jinja2==3.0.3