dependencies:
  - python=3.9
  - pip=21.0.1
  - conda-forge::tectonic=0.8.0
  - conda-forge::mamba=0.23.3
  - bioconda::snakemake-minimal=6.15.5
  - conda-forge::imagemagick
  - graphviz
  - pip:
      - click==8.0.4
      - pyyaml==6.0
      - requests==2.25.1
      - jinja2==3.0.3
      - graphviz==0.19.1
      - tabulate==0.8.10
