dependencies:
  - conda-forge::python=3.9
  - conda-forge::pip=21.0.1
  - conda-forge::tectonic=0.8.0
  - conda-forge::mamba=0.25.0
  - conda-forge::imagemagick=7.1.0.27
  - conda-forge::datrie=0.8.2
  - pip:
      - click==8.0.4
      - pyyaml==6.0
      - requests==2.25.1
      - jinja2==3.0.3
      - graphviz==0.19.1
      - snakemake==7.14.2
